### ISSUE TITLE
Can this use on esp32?

### ISSUE THREAD

**Issue by jd3096-mpy** [aajshaw/Raspberry-Pico-I2C-Slave#1]
Can this use on esp32?

**Comment by aajshaw** [comment]
Short answer: no. 

Longer answer: no, because the addresses for I2C0_BASE and I2C1_BASE are hardcoded for the memory addresses of the I2C peripherals of the Pico. If the esp32 has the same I2C peripheral as the Pico then maybe changing the base addresses might work.
